# Generated by Django 3.0.2 on 2020-02-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_title', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone_text', models.TextField(verbose_name='Номер телефона')),
                ('email_text', models.TextField(verbose_name='Емейл')),
                ('model_pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
            ],
        ),
    ]
